name: WhoAreYou
main: uk.co.oliwali.WhoAreYou.WhoAreYou
version: 0.2.0
author: oliverw92, lihad
commands:
  who:
    description: List online players
    aliases: [list,online,playerlist,listplayers,whois]
    usage: /<command> [world|player] [world]